spring:
  application:
    name: turbine-practice
server:
  port: 8089

eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.60.199:1111/eureka/
      defaultZone: http://localhost:8093/eureka/

management:
  port: 9999
turbine:
  app-config: hello-feign-client
  cluster-name-expression: new String("default") # or use "'default'"
  combine-host-port: true
